GROUP=com.stripe
VERSION_NAME=0.0.1

POM_DESCRIPTION=Generated Custom Objects SDK
POM_NAME=stripe-java
POM_ARTIFACT_ID=stripe-java
POM_PACKAGING=jar
VENDOR_NAME=Stripe

# The following is necessary for google-java-format to work with Java 16+
org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
 --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
 --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
 --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
 --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
