// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiRequestParams;
import java.util.ArrayList;
import java.util.List;
import lombok.Getter;

@Getter
public class AccountLinkCreateParams extends ApiRequestParams {
  /** The identifier of the account to create an account link for. */
  @SerializedName("account")
  String account;

  /**
   * The information the platform wants to collect from users up-front. Possible values are
   * `currently_due` and `eventually_due`.
   */
  @SerializedName("collect")
  Collect collect;

  /** Specifies which fields in the response should be expanded. */
  @SerializedName("expand")
  List<String> expand;

  /** The URL that the user will be redirected to if the account link is no longer valid. */
  @SerializedName("failure_url")
  String failureUrl;

  /** The URL that the user will be redirected to upon completing the linked flow successfully. */
  @SerializedName("success_url")
  String successUrl;

  /**
   * The type of account link the user is requesting. Possible values are
   * `custom_account_verification` or `custom_account_update`.
   */
  @SerializedName("type")
  String type;

  private AccountLinkCreateParams(
      String account,
      Collect collect,
      List<String> expand,
      String failureUrl,
      String successUrl,
      String type) {
    this.account = account;
    this.collect = collect;
    this.expand = expand;
    this.failureUrl = failureUrl;
    this.successUrl = successUrl;
    this.type = type;
  }

  public static Builder builder() {
    return new com.stripe.param.AccountLinkCreateParams.Builder();
  }

  public static class Builder {
    private String account;

    private Collect collect;

    private List<String> expand;

    private String failureUrl;

    private String successUrl;

    private String type;

    /** Finalize and obtain parameter instance from this builder. */
    public AccountLinkCreateParams build() {
      return new AccountLinkCreateParams(
          this.account, this.collect, this.expand, this.failureUrl, this.successUrl, this.type);
    }

    /**
     * Add all elements to `expand` list. A list is initialized for the first `add/addAll` call, and
     * subsequent calls adds additional elements to the original list. See {@link
     * AccountLinkCreateParams#expand} for the field documentation.
     */
    public Builder addAllExpand(List<String> elements) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.addAll(elements);
      return this;
    }

    /**
     * Add an element to `expand` list. A list is initialized for the first `add/addAll` call, and
     * subsequent calls adds additional elements to the original list. See {@link
     * AccountLinkCreateParams#expand} for the field documentation.
     */
    public Builder addExpand(String element) {
      if (this.expand == null) {
        this.expand = new ArrayList<>();
      }
      this.expand.add(element);
      return this;
    }

    /** The identifier of the account to create an account link for. */
    public Builder setAccount(String account) {
      this.account = account;
      return this;
    }

    /**
     * The information the platform wants to collect from users up-front. Possible values are
     * `currently_due` and `eventually_due`.
     */
    public Builder setCollect(Collect collect) {
      this.collect = collect;
      return this;
    }

    /** The URL that the user will be redirected to if the account link is no longer valid. */
    public Builder setFailureUrl(String failureUrl) {
      this.failureUrl = failureUrl;
      return this;
    }

    /** The URL that the user will be redirected to upon completing the linked flow successfully. */
    public Builder setSuccessUrl(String successUrl) {
      this.successUrl = successUrl;
      return this;
    }

    /**
     * The type of account link the user is requesting. Possible values are
     * `custom_account_verification` or `custom_account_update`.
     */
    public Builder setType(String type) {
      this.type = type;
      return this;
    }
  }

  public enum Collect implements ApiRequestParams.EnumParam {
    @SerializedName("currently_due")
    CURRENTLY_DUE("currently_due"),

    @SerializedName("eventually_due")
    EVENTUALLY_DUE("eventually_due");

    @Getter(onMethod = @__({@Override}))
    private final String value;

    Collect(String value) {
      this.value = value;
    }
  }
}
