// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param;

import com.stripe.net.ApiRequestParams;

public class WebhookEndpointDeleteParams extends ApiRequestParams {
  private WebhookEndpointDeleteParams() {}

  public static Builder builder() {
    return new com.stripe.param.WebhookEndpointDeleteParams.Builder();
  }

  public static class Builder {
    /** Finalize and obtain parameter instance from this builder. */
    public WebhookEndpointDeleteParams build() {
      return new WebhookEndpointDeleteParams();
    }
  }
}
