// File generated from our OpenAPI spec
package com.stripe.model.v2.signals;

import com.google.gson.annotations.SerializedName;
import com.stripe.model.HasId;
import com.stripe.model.StripeObject;
import java.time.Instant;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

/**
 * The PaymentRetryEvaluation resource represents an active or completed retry monitoring session
 * for a specific failed payment.
 */
@Getter
@Setter
@EqualsAndHashCode(callSuper = false)
public class PaymentRetryEvaluation extends StripeObject implements HasId {
  /** When the evaluation was canceled, if applicable. */
  @SerializedName("canceled_at")
  Instant canceledAt;

  /** Reason provided for canceling the evaluation. */
  @SerializedName("cancellation_reason")
  String cancellationReason;

  /** When the evaluation was created. */
  @SerializedName("created")
  Instant created;

  /** Unique identifier for the evaluation. */
  @Getter(onMethod_ = {@Override})
  @SerializedName("id")
  String id;

  /**
   * The PaymentRetrySignal resource represents a single retry recommendation generated by the ML
   * scoring model.
   */
  @SerializedName("latest_signal")
  PaymentRetrySignal latestSignal;

  /**
   * Has the value {@code true} if the object exists in live mode or the value {@code false} if the
   * object exists in test mode.
   */
  @SerializedName("livemode")
  Boolean livemode;

  /**
   * String representing the object's type. Objects of the same type share the same value of the
   * object field.
   *
   * <p>Equal to {@code v2.signals.payment_retry_evaluation}.
   */
  @SerializedName("object")
  String object;

  /** The payment intent being evaluated, if provided instead of a payment record. */
  @SerializedName("payment_intent")
  String paymentIntent;

  /** The payment record being evaluated. */
  @SerializedName("payment_record")
  String paymentRecord;

  /**
   * Current status of the evaluation.
   *
   * <p>One of {@code canceled}, {@code completed}, {@code expired}, or {@code monitoring}.
   */
  @SerializedName("status")
  String status;
}
