// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.model.issuing;

import com.stripe.model.StripeCollection;

public class CardholderCollection extends StripeCollection<Cardholder> {}
