// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.service;

import com.stripe.exception.StripeException;
import com.stripe.model.ApplePayDomain;
import com.stripe.model.ApplePayDomainCollection;
import com.stripe.net.ApiResource;
import com.stripe.net.ApiService;
import com.stripe.net.RequestOptions;
import com.stripe.param.ApplePayDomainCreateParams;
import com.stripe.param.ApplePayDomainDeleteParams;
import com.stripe.param.ApplePayDomainListParams;
import com.stripe.param.ApplePayDomainRetrieveParams;

public class ApplePayDomainService extends ApiService {
  /** Create an apple pay domain. */
  public ApplePayDomain create(ApplePayDomainCreateParams params) throws StripeException {
    return create(params, (RequestOptions) null);
  }

  /** Create an apple pay domain. */
  public ApplePayDomain create(ApplePayDomainCreateParams params, RequestOptions options)
      throws StripeException {
    String url = resourceUrl("/v1/apple_pay/domains");
    return request(ApiResource.RequestMethod.POST, url, params, ApplePayDomain.class, options);
  }

  /** Delete an apple pay domain. */
  public ApplePayDomain delete(String domain, ApplePayDomainDeleteParams params)
      throws StripeException {
    return delete(domain, params, (RequestOptions) null);
  }

  /** Delete an apple pay domain. */
  public ApplePayDomain delete(
      String domain, ApplePayDomainDeleteParams params, RequestOptions options)
      throws StripeException {
    String url = resourceUrl("/v1/apple_pay/domains/%s", domain);
    return request(ApiResource.RequestMethod.DELETE, url, params, ApplePayDomain.class, options);
  }

  /** List apple pay domains. */
  public ApplePayDomainCollection list(ApplePayDomainListParams params) throws StripeException {
    return list(params, (RequestOptions) null);
  }

  /** List apple pay domains. */
  public ApplePayDomainCollection list(ApplePayDomainListParams params, RequestOptions options)
      throws StripeException {
    String url = resourceUrl("/v1/apple_pay/domains");
    return requestCollection(url, params, ApplePayDomainCollection.class, options);
  }

  /** Retrieve an apple pay domain. */
  public ApplePayDomain retrieve(String domain, ApplePayDomainRetrieveParams params)
      throws StripeException {
    return retrieve(domain, params, (RequestOptions) null);
  }

  /** Retrieve an apple pay domain. */
  public ApplePayDomain retrieve(
      String domain, ApplePayDomainRetrieveParams params, RequestOptions options)
      throws StripeException {
    String url = resourceUrl("/v1/apple_pay/domains/%s", domain);
    return request(ApiResource.RequestMethod.GET, url, params, ApplePayDomain.class, options);
  }
}
