// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.service;

import com.stripe.exception.StripeException;
import com.stripe.model.ExchangeRate;
import com.stripe.model.ExchangeRateCollection;
import com.stripe.net.ApiResource;
import com.stripe.net.ApiService;
import com.stripe.net.RequestOptions;
import com.stripe.param.ExchangeRateListParams;
import com.stripe.param.ExchangeRateRetrieveParams;

public class ExchangeRateService extends ApiService {
  /**
   * Returns a list of objects that contain the rates at which foreign currencies are converted to
   * one another. Only shows the currencies for which Stripe supports.
   */
  public ExchangeRateCollection list(ExchangeRateListParams params) throws StripeException {
    return list(params, (RequestOptions) null);
  }

  /**
   * Returns a list of objects that contain the rates at which foreign currencies are converted to
   * one another. Only shows the currencies for which Stripe supports.
   */
  public ExchangeRateCollection list(ExchangeRateListParams params, RequestOptions options)
      throws StripeException {
    String url = resourceUrl("/v1/exchange_rates");
    return requestCollection(url, params, ExchangeRateCollection.class, options);
  }

  /** Retrieves the exchange rates from the given currency to every supported currency. */
  public ExchangeRate retrieve(String currency, ExchangeRateRetrieveParams params)
      throws StripeException {
    return retrieve(currency, params, (RequestOptions) null);
  }

  /** Retrieves the exchange rates from the given currency to every supported currency. */
  public ExchangeRate retrieve(
      String currency, ExchangeRateRetrieveParams params, RequestOptions options)
      throws StripeException {
    String url = resourceUrl("/v1/exchange_rates/%s", currency);
    return request(ApiResource.RequestMethod.GET, url, params, ExchangeRate.class, options);
  }
}
