// File generated from our OpenAPI spec
package com.stripe.service;

import com.google.gson.reflect.TypeToken;
import com.stripe.Stripe;
import com.stripe.exception.StripeException;
import com.stripe.model.InvoiceRenderingTemplate;
import com.stripe.model.StripeCollection;
import com.stripe.net.ApiRequest;
import com.stripe.net.ApiRequestParams;
import com.stripe.net.ApiResource;
import com.stripe.net.ApiService;
import com.stripe.net.BaseAddress;
import com.stripe.net.RequestOptions;
import com.stripe.net.StripeResponseGetter;
import com.stripe.param.InvoiceRenderingTemplateArchiveParams;
import com.stripe.param.InvoiceRenderingTemplateListParams;
import com.stripe.param.InvoiceRenderingTemplateRetrieveParams;
import com.stripe.param.InvoiceRenderingTemplateUnarchiveParams;

public final class InvoiceRenderingTemplateService extends ApiService {
  public InvoiceRenderingTemplateService(StripeResponseGetter responseGetter) {
    super(responseGetter);
  }

  /**
   * List all templates, ordered by creation date, with the most recently created template appearing
   * first.
   */
  public StripeCollection<InvoiceRenderingTemplate> list(InvoiceRenderingTemplateListParams params)
      throws StripeException {
    return list(params, (RequestOptions) null);
  }
  /**
   * List all templates, ordered by creation date, with the most recently created template appearing
   * first.
   */
  public StripeCollection<InvoiceRenderingTemplate> list(RequestOptions options)
      throws StripeException {
    return list((InvoiceRenderingTemplateListParams) null, options);
  }
  /**
   * List all templates, ordered by creation date, with the most recently created template appearing
   * first.
   */
  public StripeCollection<InvoiceRenderingTemplate> list() throws StripeException {
    return list((InvoiceRenderingTemplateListParams) null, (RequestOptions) null);
  }
  /**
   * List all templates, ordered by creation date, with the most recently created template appearing
   * first.
   */
  public StripeCollection<InvoiceRenderingTemplate> list(
      InvoiceRenderingTemplateListParams params, RequestOptions options) throws StripeException {
    String path = "/v1/invoice_rendering_templates";
    ApiRequest request =
        new ApiRequest(
            BaseAddress.API,
            ApiResource.RequestMethod.GET,
            path,
            ApiRequestParams.paramsToMap(params),
            options);
    return this.request(
        request, new TypeToken<StripeCollection<InvoiceRenderingTemplate>>() {}.getType());
  }
  /**
   * Retrieves an invoice rendering template with the given ID. It by default returns the latest
   * version of the template. Optionally, specify a version to see previous versions.
   */
  public InvoiceRenderingTemplate retrieve(String id, InvoiceRenderingTemplateRetrieveParams params)
      throws StripeException {
    return retrieve(id, params, (RequestOptions) null);
  }
  /**
   * Retrieves an invoice rendering template with the given ID. It by default returns the latest
   * version of the template. Optionally, specify a version to see previous versions.
   */
  public InvoiceRenderingTemplate retrieve(String id, RequestOptions options)
      throws StripeException {
    return retrieve(id, (InvoiceRenderingTemplateRetrieveParams) null, options);
  }
  /**
   * Retrieves an invoice rendering template with the given ID. It by default returns the latest
   * version of the template. Optionally, specify a version to see previous versions.
   */
  public InvoiceRenderingTemplate retrieve(String id) throws StripeException {
    return retrieve(id, (InvoiceRenderingTemplateRetrieveParams) null, (RequestOptions) null);
  }
  /**
   * Retrieves an invoice rendering template with the given ID. It by default returns the latest
   * version of the template. Optionally, specify a version to see previous versions.
   */
  public InvoiceRenderingTemplate retrieve(
      String id, InvoiceRenderingTemplateRetrieveParams params, RequestOptions options)
      throws StripeException {
    String path = String.format("/v1/invoice_rendering_templates/%s", ApiResource.urlEncodeId(id));
    ApiRequest request =
        new ApiRequest(
            BaseAddress.API,
            ApiResource.RequestMethod.GET,
            path,
            ApiRequestParams.paramsToMap(params),
            options);
    return this.request(request, InvoiceRenderingTemplate.class);
  }
  /**
   * Updates the status of an invoice rendering template to ‘archived’ so no new Stripe objects
   * (customers, invoices, etc.) can reference it. The template can also no longer be updated.
   * However, if the template is already set on a Stripe object, it will continue to be applied on
   * invoices generated by it.
   */
  public InvoiceRenderingTemplate archive(String id, InvoiceRenderingTemplateArchiveParams params)
      throws StripeException {
    return archive(id, params, (RequestOptions) null);
  }
  /**
   * Updates the status of an invoice rendering template to ‘archived’ so no new Stripe objects
   * (customers, invoices, etc.) can reference it. The template can also no longer be updated.
   * However, if the template is already set on a Stripe object, it will continue to be applied on
   * invoices generated by it.
   */
  public InvoiceRenderingTemplate archive(String id, RequestOptions options)
      throws StripeException {
    return archive(id, (InvoiceRenderingTemplateArchiveParams) null, options);
  }
  /**
   * Updates the status of an invoice rendering template to ‘archived’ so no new Stripe objects
   * (customers, invoices, etc.) can reference it. The template can also no longer be updated.
   * However, if the template is already set on a Stripe object, it will continue to be applied on
   * invoices generated by it.
   */
  public InvoiceRenderingTemplate archive(String id) throws StripeException {
    return archive(id, (InvoiceRenderingTemplateArchiveParams) null, (RequestOptions) null);
  }
  /**
   * Updates the status of an invoice rendering template to ‘archived’ so no new Stripe objects
   * (customers, invoices, etc.) can reference it. The template can also no longer be updated.
   * However, if the template is already set on a Stripe object, it will continue to be applied on
   * invoices generated by it.
   */
  public InvoiceRenderingTemplate archive(
      String id, InvoiceRenderingTemplateArchiveParams params, RequestOptions options)
      throws StripeException {
    String path =
        String.format("/v1/invoice_rendering_templates/%s/archive", ApiResource.urlEncodeId(id));
    ApiRequest request =
        new ApiRequest(
            BaseAddress.API,
            ApiResource.RequestMethod.POST,
            path,
            ApiRequestParams.paramsToMap(params),
            options);
    return this.request(request, InvoiceRenderingTemplate.class);
  }
  /** Unarchive an invoice rendering template so it can be used on new Stripe objects again. */
  public InvoiceRenderingTemplate unarchive(
      String id, InvoiceRenderingTemplateUnarchiveParams params) throws StripeException {
    return unarchive(id, params, (RequestOptions) null);
  }
  /** Unarchive an invoice rendering template so it can be used on new Stripe objects again. */
  public InvoiceRenderingTemplate unarchive(String id, RequestOptions options)
      throws StripeException {
    return unarchive(id, (InvoiceRenderingTemplateUnarchiveParams) null, options);
  }
  /** Unarchive an invoice rendering template so it can be used on new Stripe objects again. */
  public InvoiceRenderingTemplate unarchive(String id) throws StripeException {
    return unarchive(id, (InvoiceRenderingTemplateUnarchiveParams) null, (RequestOptions) null);
  }
  /** Unarchive an invoice rendering template so it can be used on new Stripe objects again. */
  public InvoiceRenderingTemplate unarchive(
      String id, InvoiceRenderingTemplateUnarchiveParams params, RequestOptions options)
      throws StripeException {
    String path =
        String.format("/v1/invoice_rendering_templates/%s/unarchive", ApiResource.urlEncodeId(id));
    ApiRequest request =
        new ApiRequest(
            BaseAddress.API,
            ApiResource.RequestMethod.POST,
            path,
            ApiRequestParams.paramsToMap(params),
            options);
    return this.request(request, InvoiceRenderingTemplate.class);
  }
  /** Serializes an InvoiceRenderingTemplate archive request into a batch job JSONL line. */
  public String serializeBatchArchive(String id, InvoiceRenderingTemplateArchiveParams params)
      throws StripeException {
    return serializeBatchArchive(id, params, (RequestOptions) null);
  }
  /** Serializes an InvoiceRenderingTemplate archive request into a batch job JSONL line. */
  public String serializeBatchArchive(
      String id, InvoiceRenderingTemplateArchiveParams params, RequestOptions options)
      throws StripeException {
    String requestId = java.util.UUID.randomUUID().toString();
    String stripeVersion = Stripe.API_VERSION;
    String stripeContext = (options != null) ? options.getStripeContext() : null;

    java.util.Map<String, String> pathParams = new java.util.LinkedHashMap<String, String>();
    pathParams.put("id", id);
    java.util.Map<String, Object> requestBody = new java.util.LinkedHashMap<>();
    requestBody.put("id", requestId);
    requestBody.put("path_params", pathParams);
    requestBody.put("params", (params != null) ? params.toMap() : null);
    requestBody.put("stripe_version", stripeVersion);
    if (stripeContext != null) {
      requestBody.put("context", stripeContext);
    }
    return ApiResource.GSON.toJson(requestBody);
  }
  /** Serializes an InvoiceRenderingTemplate unarchive request into a batch job JSONL line. */
  public String serializeBatchUnarchive(String id, InvoiceRenderingTemplateUnarchiveParams params)
      throws StripeException {
    return serializeBatchUnarchive(id, params, (RequestOptions) null);
  }
  /** Serializes an InvoiceRenderingTemplate unarchive request into a batch job JSONL line. */
  public String serializeBatchUnarchive(
      String id, InvoiceRenderingTemplateUnarchiveParams params, RequestOptions options)
      throws StripeException {
    String requestId = java.util.UUID.randomUUID().toString();
    String stripeVersion = Stripe.API_VERSION;
    String stripeContext = (options != null) ? options.getStripeContext() : null;

    java.util.Map<String, String> pathParams = new java.util.LinkedHashMap<String, String>();
    pathParams.put("id", id);
    java.util.Map<String, Object> requestBody = new java.util.LinkedHashMap<>();
    requestBody.put("id", requestId);
    requestBody.put("path_params", pathParams);
    requestBody.put("params", (params != null) ? params.toMap() : null);
    requestBody.put("stripe_version", stripeVersion);
    if (stripeContext != null) {
      requestBody.put("context", stripeContext);
    }
    return ApiResource.GSON.toJson(requestBody);
  }
}
