// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.param.checkout;

import com.google.gson.annotations.SerializedName;
import com.stripe.net.ApiRequestParams;
import lombok.Getter;

public class Foo extends ApiRequestParams {

  public static class PaymentIntentData {

    public static class Shipping {

      public static class Address {
        @SerializedName("city")
        String city;

        @SerializedName("country")
        String country;

        public static class Builder {
          String city;
          String country;

          /**
           * See documentation in {@link Address#city}.
           */
          public Builder setCity(String city) {
            this.city = city;
            return this;
          }

          public Builder setCountry(String country) {
            this.country = country;
            return this;
          }
        }
      }
    }

    public static class TransferData {
      /**
       * If specified, successful charges will be attributed to the destination account for tax
       * reporting, and the funds from charges will be transferred to the destination account. The
       * ID of the resulting transfer will be returned on the successful charge's `transfer` field.
       */
      @SerializedName("destination")
      String destination;
    }
  }

  public enum PaymentMethodType implements ApiRequestParams.EnumParam {
    @SerializedName("card")
    CARD("card");

    @Getter(onMethod = @__({@Override}))
    private final String value;

    PaymentMethodType(String value) {
      this.value = value;
    }
  }
}
