// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.model;

import com.stripe.model.checkout.Session;
import com.stripe.model.issuing.Authorization;
import com.stripe.model.issuing.CardDetails;
import com.stripe.model.issuing.CardPin;
import com.stripe.model.issuing.Cardholder;
import com.stripe.model.issuing.Settlement;
import com.stripe.model.issuing.Transaction;
import com.stripe.model.issuing.Verification;
import com.stripe.model.radar.ValueList;
import com.stripe.model.radar.ValueListItem;
import com.stripe.model.reporting.ReportRun;
import com.stripe.model.reporting.ReportType;
import com.stripe.model.sigma.ScheduledQueryRun;
import com.stripe.model.terminal.ConnectionToken;
import com.stripe.model.terminal.Location;
import com.stripe.model.terminal.Reader;
import java.util.HashMap;
import java.util.Map;

/**
 * Event data class look up used in {@link EventDataDeserializer}. The key to look up is `object`
 * string of the model.
 */
final class EventDataClassLookup {
  private static final Map<String, Class<? extends StripeObject>> classLookup = new HashMap<>();

  static {
    classLookup.put("account", Account.class);
    classLookup.put("account_link", AccountLink.class);
    classLookup.put("alipay_account", AlipayAccount.class);
    classLookup.put("apple_pay_domain", ApplePayDomain.class);
    classLookup.put("application", Application.class);
    classLookup.put("application_fee", ApplicationFee.class);
    classLookup.put("balance", Balance.class);
    classLookup.put("balance_transaction", BalanceTransaction.class);
    classLookup.put("bank_account", BankAccount.class);
    classLookup.put("bitcoin_receiver", BitcoinReceiver.class);
    classLookup.put("bitcoin_transaction", BitcoinTransaction.class);
    classLookup.put("card", Card.class);
    classLookup.put("charge", Charge.class);
    classLookup.put("checkout.session", Session.class);
    classLookup.put("connect_collection_transfer", ConnectCollectionTransfer.class);
    classLookup.put("country_spec", CountrySpec.class);
    classLookup.put("coupon", Coupon.class);
    classLookup.put("customer", Customer.class);
    classLookup.put("discount", Discount.class);
    classLookup.put("dispute", Dispute.class);
    classLookup.put("ephemeral_key", EphemeralKey.class);
    classLookup.put("event", Event.class);
    classLookup.put("exchange_rate", ExchangeRate.class);
    classLookup.put("fee_refund", FeeRefund.class);
    classLookup.put("file", File.class);
    classLookup.put("file_link", FileLink.class);
    classLookup.put("invoice", Invoice.class);
    classLookup.put("invoiceitem", InvoiceItem.class);
    classLookup.put("issuer_fraud_record", IssuerFraudRecord.class);
    classLookup.put("issuing.authorization", Authorization.class);
    classLookup.put("issuing.card", com.stripe.model.issuing.Card.class);
    classLookup.put("issuing.card_details", CardDetails.class);
    classLookup.put("issuing.card_pin", CardPin.class);
    classLookup.put("issuing.cardholder", Cardholder.class);
    classLookup.put("issuing.dispute", com.stripe.model.issuing.Dispute.class);
    classLookup.put("issuing.settlement", Settlement.class);
    classLookup.put("issuing.transaction", Transaction.class);
    classLookup.put("issuing.verification", Verification.class);
    classLookup.put("line_item", InvoiceLineItem.class);
    classLookup.put("login_link", LoginLink.class);
    classLookup.put("notification_event_data", EventData.class);
    classLookup.put("order", Order.class);
    classLookup.put("order_item", OrderItem.class);
    classLookup.put("order_return", OrderReturn.class);
    classLookup.put("payment_intent", PaymentIntent.class);
    classLookup.put("payment_method", PaymentMethod.class);
    classLookup.put("payout", Payout.class);
    classLookup.put("person", Person.class);
    classLookup.put("plan", Plan.class);
    classLookup.put("product", Product.class);
    classLookup.put("radar.value_list", ValueList.class);
    classLookup.put("radar.value_list_item", ValueListItem.class);
    classLookup.put("recipient", Recipient.class);
    classLookup.put("recipient_transfer", RecipientTransfer.class);
    classLookup.put("refund", Refund.class);
    classLookup.put("reporting.report_run", ReportRun.class);
    classLookup.put("reporting.report_type", ReportType.class);
    classLookup.put("reserve_transaction", ReserveTransaction.class);
    classLookup.put("review", Review.class);
    classLookup.put("scheduled_query_run", ScheduledQueryRun.class);
    classLookup.put("sku", Sku.class);
    classLookup.put("source", Source.class);
    classLookup.put("source_mandate_notification", SourceMandateNotification.class);
    classLookup.put("source_transaction", SourceTransaction.class);
    classLookup.put("subscription", Subscription.class);
    classLookup.put("subscription_item", SubscriptionItem.class);
    classLookup.put("terminal.connection_token", ConnectionToken.class);
    classLookup.put("terminal.location", Location.class);
    classLookup.put("terminal.reader", Reader.class);
    classLookup.put("three_d_secure", ThreeDSecure.class);
    classLookup.put("token", Token.class);
    classLookup.put("topup", Topup.class);
    classLookup.put("transfer", Transfer.class);
    classLookup.put("transfer_reversal", TransferReversal.class);
    classLookup.put("usage_record", UsageRecord.class);
    classLookup.put("usage_record_summary", UsageRecordSummary.class);
    classLookup.put("webhook_endpoint", WebhookEndpoint.class);
  }

  public static Class<? extends StripeObject> findClass(String objectType) {
    return classLookup.get(objectType);
  }
}
