// Generated by com.stripe.generator.entity.SdkBuilder

package com.stripe.model;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@EqualsAndHashCode(callSuper = false)
public class SourceTypeWechat extends StripeObject {
  String nativeUrl;

  String prepayId;

  String qrCodeUrl;

  String statementDescriptor;
}
