// File generated from our OpenAPI spec
package com.stripe.model.v2;

import com.stripe.model.v2.core.EventNotification;
import java.util.HashMap;
import java.util.Map;

/**
 * Event data class look up used in event deserialization. The key to look up is `object` string of
 * the model.
 *
 * <p>For internal use by Stripe SDK only.
 */
public final class EventNotificationClassLookup {
  public static final Map<String, Class<? extends EventNotification>> eventClassLookup =
      new HashMap<>();

  static {
    eventClassLookup.put(
        "v1.billing.meter.error_report_triggered",
        com.stripe.events.V1BillingMeterErrorReportTriggeredEventNotification.class);
    eventClassLookup.put(
        "v1.billing.meter.no_meter_found",
        com.stripe.events.V1BillingMeterNoMeterFoundEventNotification.class);
    eventClassLookup.put(
        "v2.billing.cadence.billed",
        com.stripe.events.V2BillingCadenceBilledEventNotification.class);
    eventClassLookup.put(
        "v2.billing.cadence.canceled",
        com.stripe.events.V2BillingCadenceCanceledEventNotification.class);
    eventClassLookup.put(
        "v2.billing.cadence.created",
        com.stripe.events.V2BillingCadenceCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.license_fee.created",
        com.stripe.events.V2BillingLicenseFeeCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.license_fee.updated",
        com.stripe.events.V2BillingLicenseFeeUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.license_fee_version.created",
        com.stripe.events.V2BillingLicenseFeeVersionCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.licensed_item.created",
        com.stripe.events.V2BillingLicensedItemCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.licensed_item.updated",
        com.stripe.events.V2BillingLicensedItemUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.metered_item.created",
        com.stripe.events.V2BillingMeteredItemCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.metered_item.updated",
        com.stripe.events.V2BillingMeteredItemUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan.created",
        com.stripe.events.V2BillingPricingPlanCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan.updated",
        com.stripe.events.V2BillingPricingPlanUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_component.created",
        com.stripe.events.V2BillingPricingPlanComponentCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_component.updated",
        com.stripe.events.V2BillingPricingPlanComponentUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_subscription.collection_awaiting_customer_action",
        com.stripe.events
            .V2BillingPricingPlanSubscriptionCollectionAwaitingCustomerActionEventNotification
            .class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_subscription.collection_current",
        com.stripe.events.V2BillingPricingPlanSubscriptionCollectionCurrentEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_subscription.collection_past_due",
        com.stripe.events.V2BillingPricingPlanSubscriptionCollectionPastDueEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_subscription.collection_paused",
        com.stripe.events.V2BillingPricingPlanSubscriptionCollectionPausedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_subscription.collection_unpaid",
        com.stripe.events.V2BillingPricingPlanSubscriptionCollectionUnpaidEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_subscription.servicing_activated",
        com.stripe.events.V2BillingPricingPlanSubscriptionServicingActivatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_subscription.servicing_canceled",
        com.stripe.events.V2BillingPricingPlanSubscriptionServicingCanceledEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_subscription.servicing_paused",
        com.stripe.events.V2BillingPricingPlanSubscriptionServicingPausedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.pricing_plan_version.created",
        com.stripe.events.V2BillingPricingPlanVersionCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card.created",
        com.stripe.events.V2BillingRateCardCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card.updated",
        com.stripe.events.V2BillingRateCardUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_rate.created",
        com.stripe.events.V2BillingRateCardRateCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.activated",
        com.stripe.events.V2BillingRateCardSubscriptionActivatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.canceled",
        com.stripe.events.V2BillingRateCardSubscriptionCanceledEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.collection_awaiting_customer_action",
        com.stripe.events
            .V2BillingRateCardSubscriptionCollectionAwaitingCustomerActionEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.collection_current",
        com.stripe.events.V2BillingRateCardSubscriptionCollectionCurrentEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.collection_past_due",
        com.stripe.events.V2BillingRateCardSubscriptionCollectionPastDueEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.collection_paused",
        com.stripe.events.V2BillingRateCardSubscriptionCollectionPausedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.collection_unpaid",
        com.stripe.events.V2BillingRateCardSubscriptionCollectionUnpaidEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.servicing_activated",
        com.stripe.events.V2BillingRateCardSubscriptionServicingActivatedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.servicing_canceled",
        com.stripe.events.V2BillingRateCardSubscriptionServicingCanceledEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_subscription.servicing_paused",
        com.stripe.events.V2BillingRateCardSubscriptionServicingPausedEventNotification.class);
    eventClassLookup.put(
        "v2.billing.rate_card_version.created",
        com.stripe.events.V2BillingRateCardVersionCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account.closed", com.stripe.events.V2CoreAccountClosedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account.created", com.stripe.events.V2CoreAccountCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account.updated", com.stripe.events.V2CoreAccountUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account[configuration.card_creator].capability_status_updated",
        com.stripe.events
            .V2CoreAccountIncludingConfigurationCardCreatorCapabilityStatusUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.card_creator].updated",
        com.stripe.events.V2CoreAccountIncludingConfigurationCardCreatorUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.customer].capability_status_updated",
        com.stripe.events
            .V2CoreAccountIncludingConfigurationCustomerCapabilityStatusUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.customer].updated",
        com.stripe.events.V2CoreAccountIncludingConfigurationCustomerUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.merchant].capability_status_updated",
        com.stripe.events
            .V2CoreAccountIncludingConfigurationMerchantCapabilityStatusUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.merchant].updated",
        com.stripe.events.V2CoreAccountIncludingConfigurationMerchantUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.recipient].capability_status_updated",
        com.stripe.events
            .V2CoreAccountIncludingConfigurationRecipientCapabilityStatusUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.recipient].updated",
        com.stripe.events.V2CoreAccountIncludingConfigurationRecipientUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.storer].capability_status_updated",
        com.stripe.events
            .V2CoreAccountIncludingConfigurationStorerCapabilityStatusUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.account[configuration.storer].updated",
        com.stripe.events.V2CoreAccountIncludingConfigurationStorerUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account[defaults].updated",
        com.stripe.events.V2CoreAccountIncludingDefaultsUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account[identity].updated",
        com.stripe.events.V2CoreAccountIncludingIdentityUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account[requirements].updated",
        com.stripe.events.V2CoreAccountIncludingRequirementsUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account_link.returned",
        com.stripe.events.V2CoreAccountLinkReturnedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account_person.created",
        com.stripe.events.V2CoreAccountPersonCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account_person.deleted",
        com.stripe.events.V2CoreAccountPersonDeletedEventNotification.class);
    eventClassLookup.put(
        "v2.core.account_person.updated",
        com.stripe.events.V2CoreAccountPersonUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.claimable_sandbox.claimed",
        com.stripe.events.V2CoreClaimableSandboxClaimedEventNotification.class);
    eventClassLookup.put(
        "v2.core.claimable_sandbox.created",
        com.stripe.events.V2CoreClaimableSandboxCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.core.claimable_sandbox.expired",
        com.stripe.events.V2CoreClaimableSandboxExpiredEventNotification.class);
    eventClassLookup.put(
        "v2.core.claimable_sandbox.expiring",
        com.stripe.events.V2CoreClaimableSandboxExpiringEventNotification.class);
    eventClassLookup.put(
        "v2.core.claimable_sandbox.sandbox_details_owner_account_updated",
        com.stripe.events.V2CoreClaimableSandboxSandboxDetailsOwnerAccountUpdatedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.event_destination.ping",
        com.stripe.events.V2CoreEventDestinationPingEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.api_error.firing",
        com.stripe.events.V2CoreHealthApiErrorFiringEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.api_error.resolved",
        com.stripe.events.V2CoreHealthApiErrorResolvedEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.api_latency.firing",
        com.stripe.events.V2CoreHealthApiLatencyFiringEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.api_latency.resolved",
        com.stripe.events.V2CoreHealthApiLatencyResolvedEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.authorization_rate_drop.firing",
        com.stripe.events.V2CoreHealthAuthorizationRateDropFiringEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.authorization_rate_drop.resolved",
        com.stripe.events.V2CoreHealthAuthorizationRateDropResolvedEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.event_generation_failure.resolved",
        com.stripe.events.V2CoreHealthEventGenerationFailureResolvedEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.fraud_rate.increased",
        com.stripe.events.V2CoreHealthFraudRateIncreasedEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.issuing_authorization_request_errors.firing",
        com.stripe.events.V2CoreHealthIssuingAuthorizationRequestErrorsFiringEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.health.issuing_authorization_request_errors.resolved",
        com.stripe.events.V2CoreHealthIssuingAuthorizationRequestErrorsResolvedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.health.issuing_authorization_request_timeout.firing",
        com.stripe.events.V2CoreHealthIssuingAuthorizationRequestTimeoutFiringEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.health.issuing_authorization_request_timeout.resolved",
        com.stripe.events.V2CoreHealthIssuingAuthorizationRequestTimeoutResolvedEventNotification
            .class);
    eventClassLookup.put(
        "v2.core.health.payment_method_error.firing",
        com.stripe.events.V2CoreHealthPaymentMethodErrorFiringEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.payment_method_error.resolved",
        com.stripe.events.V2CoreHealthPaymentMethodErrorResolvedEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.traffic_volume_drop.firing",
        com.stripe.events.V2CoreHealthTrafficVolumeDropFiringEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.traffic_volume_drop.resolved",
        com.stripe.events.V2CoreHealthTrafficVolumeDropResolvedEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.webhook_latency.firing",
        com.stripe.events.V2CoreHealthWebhookLatencyFiringEventNotification.class);
    eventClassLookup.put(
        "v2.core.health.webhook_latency.resolved",
        com.stripe.events.V2CoreHealthWebhookLatencyResolvedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.adjustment.created",
        com.stripe.events.V2MoneyManagementAdjustmentCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.financial_account.created",
        com.stripe.events.V2MoneyManagementFinancialAccountCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.financial_account.updated",
        com.stripe.events.V2MoneyManagementFinancialAccountUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.financial_address.activated",
        com.stripe.events.V2MoneyManagementFinancialAddressActivatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.financial_address.failed",
        com.stripe.events.V2MoneyManagementFinancialAddressFailedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.inbound_transfer.available",
        com.stripe.events.V2MoneyManagementInboundTransferAvailableEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.inbound_transfer.bank_debit_failed",
        com.stripe.events.V2MoneyManagementInboundTransferBankDebitFailedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.inbound_transfer.bank_debit_processing",
        com.stripe.events.V2MoneyManagementInboundTransferBankDebitProcessingEventNotification
            .class);
    eventClassLookup.put(
        "v2.money_management.inbound_transfer.bank_debit_queued",
        com.stripe.events.V2MoneyManagementInboundTransferBankDebitQueuedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.inbound_transfer.bank_debit_returned",
        com.stripe.events.V2MoneyManagementInboundTransferBankDebitReturnedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.inbound_transfer.bank_debit_succeeded",
        com.stripe.events.V2MoneyManagementInboundTransferBankDebitSucceededEventNotification
            .class);
    eventClassLookup.put(
        "v2.money_management.outbound_payment.canceled",
        com.stripe.events.V2MoneyManagementOutboundPaymentCanceledEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_payment.created",
        com.stripe.events.V2MoneyManagementOutboundPaymentCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_payment.failed",
        com.stripe.events.V2MoneyManagementOutboundPaymentFailedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_payment.posted",
        com.stripe.events.V2MoneyManagementOutboundPaymentPostedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_payment.returned",
        com.stripe.events.V2MoneyManagementOutboundPaymentReturnedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_payment.updated",
        com.stripe.events.V2MoneyManagementOutboundPaymentUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_transfer.canceled",
        com.stripe.events.V2MoneyManagementOutboundTransferCanceledEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_transfer.created",
        com.stripe.events.V2MoneyManagementOutboundTransferCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_transfer.failed",
        com.stripe.events.V2MoneyManagementOutboundTransferFailedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_transfer.posted",
        com.stripe.events.V2MoneyManagementOutboundTransferPostedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_transfer.returned",
        com.stripe.events.V2MoneyManagementOutboundTransferReturnedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.outbound_transfer.updated",
        com.stripe.events.V2MoneyManagementOutboundTransferUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.payout_method.updated",
        com.stripe.events.V2MoneyManagementPayoutMethodUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_credit.available",
        com.stripe.events.V2MoneyManagementReceivedCreditAvailableEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_credit.failed",
        com.stripe.events.V2MoneyManagementReceivedCreditFailedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_credit.returned",
        com.stripe.events.V2MoneyManagementReceivedCreditReturnedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_credit.succeeded",
        com.stripe.events.V2MoneyManagementReceivedCreditSucceededEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_debit.canceled",
        com.stripe.events.V2MoneyManagementReceivedDebitCanceledEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_debit.failed",
        com.stripe.events.V2MoneyManagementReceivedDebitFailedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_debit.pending",
        com.stripe.events.V2MoneyManagementReceivedDebitPendingEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_debit.succeeded",
        com.stripe.events.V2MoneyManagementReceivedDebitSucceededEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.received_debit.updated",
        com.stripe.events.V2MoneyManagementReceivedDebitUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.recipient_verification.created",
        com.stripe.events.V2MoneyManagementRecipientVerificationCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.recipient_verification.updated",
        com.stripe.events.V2MoneyManagementRecipientVerificationUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.transaction.created",
        com.stripe.events.V2MoneyManagementTransactionCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.money_management.transaction.updated",
        com.stripe.events.V2MoneyManagementTransactionUpdatedEventNotification.class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.attempt_failed",
        com.stripe.events.V2PaymentsOffSessionPaymentAttemptFailedEventNotification.class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.attempt_started",
        com.stripe.events.V2PaymentsOffSessionPaymentAttemptStartedEventNotification.class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.authorization_attempt_failed",
        com.stripe.events.V2PaymentsOffSessionPaymentAuthorizationAttemptFailedEventNotification
            .class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.authorization_attempt_started",
        com.stripe.events.V2PaymentsOffSessionPaymentAuthorizationAttemptStartedEventNotification
            .class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.canceled",
        com.stripe.events.V2PaymentsOffSessionPaymentCanceledEventNotification.class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.created",
        com.stripe.events.V2PaymentsOffSessionPaymentCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.failed",
        com.stripe.events.V2PaymentsOffSessionPaymentFailedEventNotification.class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.requires_capture",
        com.stripe.events.V2PaymentsOffSessionPaymentRequiresCaptureEventNotification.class);
    eventClassLookup.put(
        "v2.payments.off_session_payment.succeeded",
        com.stripe.events.V2PaymentsOffSessionPaymentSucceededEventNotification.class);
    eventClassLookup.put(
        "v2.reporting.report_run.created",
        com.stripe.events.V2ReportingReportRunCreatedEventNotification.class);
    eventClassLookup.put(
        "v2.reporting.report_run.failed",
        com.stripe.events.V2ReportingReportRunFailedEventNotification.class);
    eventClassLookup.put(
        "v2.reporting.report_run.succeeded",
        com.stripe.events.V2ReportingReportRunSucceededEventNotification.class);
    eventClassLookup.put(
        "v2.reporting.report_run.updated",
        com.stripe.events.V2ReportingReportRunUpdatedEventNotification.class);
  }
}
