// File generated from our OpenAPI spec
package com.stripe.events;

import com.google.gson.annotations.SerializedName;
import com.stripe.exception.StripeException;
import com.stripe.model.v2.billing.Cadence;
import com.stripe.model.v2.core.Event;
import com.stripe.model.v2.core.Event.RelatedObject;
import java.util.List;
import lombok.Getter;
import lombok.Setter;

@Getter
public final class V2BillingCadenceBilledEvent extends Event {
  /** Data for the v2.billing.cadence.billed event. */
  @SerializedName("data")
  V2BillingCadenceBilledEvent.EventData data;

  @Getter
  @Setter
  public static final class EventData {
    /** The IDs of the invoices that were generated by the tick for this Cadence. */
    @SerializedName("invoices")
    List<String> invoices;
  }

  @SerializedName("related_object")

  /** Object containing the reference to API resource relevant to the event. */
  RelatedObject relatedObject;

  /** Retrieves the related object from the API. Make an API request on every call. */
  public Cadence fetchRelatedObject() throws StripeException {
    return (Cadence) super.fetchRelatedObject(this.relatedObject);
  }
}
